AllCops:
  Exclude:
    - '**/*.html.erb'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  AutoCorrect: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
